<h2> Get to Know a Numpy Array </h2>

In [22]:
import numpy as np

A = np.array(
    [
        [11, 12],
        [21, 22],
        [31, 32]
    ]
    )

In [23]:
type(A)

numpy.ndarray

In [24]:
A.shape

(3, 2)

In [25]:
A.ndim

2

In [26]:
A[1]

array([21, 22])

<h3>Two Types of Multiplication</h3>

In [27]:
array1 = np.array([
    [11,12],
    [21,22]
])

In [28]:
array2 = np.array([
    [1,0],
    [0,1]
])

In [29]:
np.multiply(array1, array2)

array([[11,  0],
       [ 0, 22]])

In [30]:
multiply_array = array1 * array2

multiply_array

array([[11,  0],
       [ 0, 22]])

In [31]:
dot_array = np.dot(array1, array2)

dot_array

array([[11, 12],
       [21, 22]])

In [32]:
A = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])

In [33]:
B = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [34]:
np.dot(A,B)

ValueError: shapes (4,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

<hr>
<h2 id="access">Accessing different elements of a Numpy Array</h2>

We can use rectangular brackets to access the different elements of the array. The correspondence between the rectangular brackets and the list and the rectangular representation is shown in the following figure for a 3x3 array:  


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoEg.png" width="500">


We can access the 2nd-row, 3rd column as shown in the following figure:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFT.png" width="400">


 We simply use the square brackets and the indices corresponding to the element we would like:


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [35]:
a = [
    [11,12,13],
    [21,22,23],
    [31,32,33]
]

In [36]:
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [37]:
A = np.array(a)

In [38]:
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [39]:
A.shape

(3, 3)

In [40]:
A.ndim

2

In [41]:
A.size

9

In [42]:
A[1,2]

23

In [43]:
A[1][2]

23

We can also use slicing in numpy arrays. Consider the following figure. We would like to obtain the first two columns in the first row

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFSF.png" width="400">



In [44]:
A[0][0:2]

array([11, 12])

In [46]:
A[0:2,2]

array([13, 23])

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/2D_numpy.png" width="550"><br />


<h2 id="op">Basic Operations</h2>


We can also add arrays. The process is identical to matrix addition. Matrix addition of <code>X</code> and <code>Y</code> is shown in the following figure:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoAdd.png" width="500">


In [47]:
X = np.array(
    [
        [1,0],
        [0,1]
    ]
)

In [48]:
X

array([[1, 0],
       [0, 1]])

In [49]:
Y = np.array(
    [
        [2,1],
        [1,2]
    ]
)

In [50]:
Y

array([[2, 1],
       [1, 2]])

In [51]:
Z = X + Y

In [52]:
Z

array([[3, 1],
       [1, 3]])

Multiplying a numpy array by a scaler is identical to multiplying a matrix by a scaler. If we multiply the matrix <code>Y</code> by the scaler 2, we simply multiply every element in the matrix by 2, as shown in the figure.


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoDb.png" width="500">


In [53]:
Y = np.array(
    [
        [2,1],
        [1,2]
    ]
)

In [54]:
Y

array([[2, 1],
       [1, 2]])

In [55]:
Z = 2 * Y

In [56]:
Z

array([[4, 2],
       [2, 4]])

Multiplication of two arrays corresponds to an element-wise product or <em>Hadamard product</em>. Consider matrix <code>X</code> and <code>Y</code>. The Hadamard product corresponds to multiplying each of the elements in the same position, i.e. multiplying elements contained in the same color boxes together. The result is a new matrix that is the same size as matrix <code>Y</code> or <code>X</code>, as shown in the following figure.


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoMul.png" width="500">
