<h2 id="numpy">What is Numpy?</h2>

NumPy is a Python library used for working with arrays, linear algebra, fourier transform, and matrices.A numpy array is similar to a list. NumPy stands for Numerical Python and it is an open source project.The array object in NumPy is called **ndarray**, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

NumPy is usually imported under the np alias.

It's usually fixed in size and each element is of the same type. We can cast a list to a numpy array by first importing `numpy`:

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5]

In [4]:
x = np.array(a)

In [5]:
type(x)

numpy.ndarray

In [6]:
x.shape

(5,)

In [7]:
x.dtype

dtype('int32')

In [9]:
x.mean()

3.0

In [10]:
np.array([1,-1]) * np.array([1,1]) #perkalian metrik, metrik atas dikali dengan atas, bawah dengan bawah

array([ 1, -1])

In [12]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

In [27]:
a = ["0", 1, "two", "3", 4]

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumOneList.png" width="660">

In [15]:
print("a[0]:", a[0])

a[0]: 0


In [16]:
print("a[1]:", a[1])

a[1]: 1


In [17]:
print("a[2]:", a[2])

a[2]: two


In [18]:
print("a[3]:", a[3])

a[3]: 3


In [19]:
print("a[4]:", a[4])

a[4]: 4


In [32]:
x = np.array([0,1,2,3,4])

In [33]:
x

array([0, 1, 2, 3, 4])

In [34]:
print(np.__version__)

1.25.0


In [35]:
type(x)

numpy.ndarray

In [36]:
x.dtype

dtype('int32')

In [49]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

In [50]:
type(b)

numpy.ndarray

In [51]:
b.dtype

dtype('float64')

In [52]:
c = np.array([20, 1, 2, 3, 4])

In [53]:
c

array([20,  1,  2,  3,  4])

In [54]:
c[0] = 100

In [55]:
c

array([100,   1,   2,   3,   4])

In [56]:
c[4] = 0

In [57]:
c

array([100,   1,   2,   3,   0])

In [58]:
g = np.array([10, 2, 30, 40, 50])

In [59]:
g[1] = 20

In [60]:
g

array([10, 20, 30, 40, 50])

In [61]:
d = g[1:4]

In [62]:
d

array([20, 30, 40])

In [63]:
c[3:5] = 300,400

In [64]:
c

array([100,   1,   2, 300, 400])

In [66]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

We can also define the steps in slicing, like this: [start:end:step].

In [67]:
print(arr[1:5:2])

[2 4]


In [68]:
print(arr[:4])

[1 2 3 4]


In [69]:
print(arr[1:5:])

[2 3 4 5]


In [70]:
arr = np.array([1,2,3,4,5,6,7,8])

In [72]:
print(arr[1:8:2])

[2 4 6 8]


In [73]:
select = [0, 2, 3, 4]

In [74]:
select

[0, 2, 3, 4]

In [75]:
d = c[select]

In [76]:
d

array([100,   2, 300, 400])

In [77]:
c[select] = 100000

In [78]:
c

array([100000,      1, 100000, 100000, 100000])

In [79]:
a = np.array([0, 1, 2, 3, 4])

In [80]:
a

array([0, 1, 2, 3, 4])

In [81]:
a.size

5

In [82]:
a.ndim

1

In [83]:
a.shape

(5,)

In [84]:
b = np.array([10, 20, 30, 40, 50, 60, 70])

In [85]:
b.shape

(7,)

In [86]:
b.size

7

In [87]:
b.ndim

1

In [88]:
a = np.array([1, -1, 1, -1])

In [89]:
mean = a.mean()

In [90]:
mean

0.0

In [91]:
standard_deviation = a.std()

In [92]:
standard_deviation

1.0

In [94]:
z = np.array([-1, 2, 3, 4, 5])

In [96]:
z

array([-1,  2,  3,  4,  5])

In [99]:
max_z = z.max()

In [100]:
max_z

5

In [101]:
min_z = z.min()

In [102]:
min_z

-1

In [103]:
y = np.array([-10, 201, 43, 94, 502])

In [105]:
max_y = y.max()

In [106]:
min_y = y.min()

In [107]:
Sum = (max_y + min_y)

In [109]:
Sum

492

In [110]:
u = np.array([1,0])

In [111]:
u

array([1, 0])

In [112]:
v = np.array([0, 1])

In [113]:
v

array([0, 1])

In [114]:
add = np.add(u, v)

In [115]:
add

array([1, 1])